# Generated by Django 5.1.5 on 2026-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('User', 'User')], default=12, max_length=10),
            preserve_default=False,
        ),
    ]
