# Generated by Django 5.1.5 on 2026-03-16 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announce_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
