# Generated by Django 5.1.5 on 2026-03-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_announcement_announce_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleave',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
