# Generated by Django 5.1.5 on 2026-03-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userleave_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleave',
            name='notified',
        ),
    ]
